version: '3.7'
services:
  mysql:
    image: mysql:latest
    container_name: mysql
    command: --default-authentication-plugin=mysql_native_password
    environment:
      - MYSQL_ROOT_PASSWORD= rootpassword
    ports:
      - 3306:3306
    volumes:
      - mysql_db_data_container:/var/lib/mysql
  

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    ports:
      - 9090:9090
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    command: 
      - --config.file=/etc/prometheus/prometheus.yml

  mysqld-exporter:
    image: docker.io/bitnami/mysqld-exporter:0
    ports:
      - 9104:9104
    environment:
      - DATA_SOURCE_NAME=root:rootpassword@(mysql)/
volumes:
  mysql_db_data_container:
