server:
  log_level: debug

metrics:
  wal_directory: /tmp/wal
  global:
    scrape_interval: 15s
    remote_write:
    - url: http://receive:10908/api/v1/receive
  configs:
    - name: agent
      scrape_configs:
        - job_name: agent
          static_configs:
            - targets: ['localhost:12345']
        #- job_name: mysql
          #static_configs:
            #- targets: ['host.docker.internal:9104']
integrations:
    cadvisor:
     enabled: true
     enabled_metrics:
     - percpu
     #   disabled_metrics: