version: '3.7'
services:


  receive:
    image: thanosio/thanos:v0.25.0
    volumes:
      - ./thanos/:/etc/thanos/
    ports:
      - "10907:10907"
      - "10909:10909"
      - "10908:10908"
    command:
      - "receive"
      - "--debug.name=receive"
      - "--log.level=debug"
      - "--receive.local-endpoint=\"receive:10909\""
      - "--remote-write.address=0.0.0.0:10908"
      - "--label=receive_cluster=\"thanos\""
      - "--grpc-address=0.0.0.0:10907"
      - "--http-address=0.0.0.0:10909"
    volumes:
      - ./thanos/:/etc/thanos/
      - receive:/data

  query0: #https://github.com/thanos-io/thanos/blob/main/docs/components/query.md
    image: thanosio/thanos:v0.25.0
    container_name: thanos-query0
    ports:
      - "10904:10904"
    command:
      - "query"
      - "--debug.name=query0"
      - "--log.level=debug"
      - "--grpc-address=0.0.0.0:10903"
      - "--grpc-grace-period=1s"
      - "--http-address=0.0.0.0:10904"
      - "--http-grace-period=1s"
      - "--query.replica-label=prometheus"
      - "--store=sidecar0:10901"
      - "--store=sidecar1:10911"
      - "--store=store:10905"
      - "--store=receive:10907"
    depends_on:
      - receive

  agent:
    image: grafana/agent:latest
    volumes:
      - ./agent-config.yml:/etc/agent-config/agent.yaml
    entrypoint:
      - /bin/agent
      - -config.file=/etc/agent-config/agent.yaml
      - -metrics.wal-directory=/tmp/agent/wal
      - -config.expand-env
      - -config.enable-read-api
    environment:
      - MYSQL_HOST= localhost:3306
    #volumes:
      #- //var/run/docker.sock://var/run/docker.sock
    ports:
      - "12345:12345"
    depends_on:
      - receive

  grafana:
    image: grafana/grafana
    volumes:
      - ./grafanaprovisioning/datasources:/etc/grafana/provisioning/datasources
    ports:
      - "3000:3000"
    links:
      - query0
volumes:
  mysql_db_data_container1:
  receive: 
