server:
  log_level: debug

metrics:
  wal_directory: /tmp/wal
  global:
    scrape_interval: 15s
    remote_write:
    - url: http://cortex:9009/api/prom/push
  configs:
    - name: agent
      scrape_configs:
        - job_name: agent
          static_configs:
            - targets: ['localhost:12345']
    - name: cortex
      scrape_configs:
        - job_name: cortex
          static_configs:
            - targets: ['host.docker.internal:9009']
integrations:
    cadvisor:
     enabled: true
     enabled_metrics:
     - percpu
     #   disabled_metrics:
    windows_exporter:
     enabled: true
     collected_metrics:
     - cpu
     #   disabled_metrics:
