# This file provisions datasources when grafana is starting.
apiVersion: 1

datasources:

  - name: Cortex3
    type: prometheus
    access: proxy
    orgId: 1
    url: http://cortex3:9009/api/prom
    isDefault:
    version: 1
    editable: true
