{
 "title": "Tomcat dashboard",
 "description": "Tomcat dashboard using metrics from prometheus JMX exporter, with drill down per job > instance",
 "tags": [ "Tomcat8" ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "job", "label": "Job", "query": "${VAR_JOB}" },
   {
    "name": "instance",
    "label": "Instance",
    "query": "label_values(jvm_info{job=\"$job\"}, instance)"
   },
   {
    "name": "protocol",
    "label": "Protocol",
    "query": "label_values(tomcat_bytesreceived_total{job=\"$job\", instance=~\"$instance\"}, protocol)"
   }
  ]
 },
 "panels": [
  {
   "title": "Server info",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "tomcat_serverinfo{job=\"$job\", instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "Traffic / 1 min. rate",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 4 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "increase(tomcat_bytesreceived_total{job=\"$job\", instance=~\"$instance\", protocol=~\"$protocol\"}[5m]) / 5",
     "legendFormat": "Received {{protocol}}[{{port}}] instance={{instance}} "
    },
    {
     "expr": "increase(tomcat_bytessent_total{job=\"$job\", instance=~\"$instance\", protocol=~\"$protocol\"}[5m]) / 5",
     "legendFormat": "Sent {{protocol}}[{{port}}] instance={{instance}} "
    }
   ]
  },
  {
   "title": "Request count / 1 min. rate",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 4 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(tomcat_requestcount_total{job=\"$job\", instance=~\"$instance\", protocol=~\"$protocol\"}[5m]) / 5",
     "legendFormat": "Request {{protocol}}[{{port}}] instance={{instance}} "
    },
    {
     "expr": "increase(tomcat_errorcount_total{job=\"$job\", instance=~\"$instance\", protocol=~\"$protocol\"}[5m]) / 5",
     "legendFormat": "Error {{protocol}}[{{port}}] instance={{instance}} "
    }
   ]
  },
  {
   "title": "Session count / 1 min. rate",
   "type": "graph",
   "gridPos": { "h": 9, "w": 20, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(increase(tomcat_session_sessioncounter_total{job=\"$job\", instance=~\"$instance\"}[5m]) / 5)",
     "legendFormat": "New"
    },
    {
     "expr": "sum(increase(tomcat_session_expiredsessions_total{job=\"$job\", instance=~\"$instance\"}[5m]) / 5)",
     "legendFormat": "Expired"
    },
    {
     "expr": "sum(increase(tomcat_session_rejectedsessions_total{job=\"$job\", instance=~\"$instance\"}[5m]) / 5)",
     "legendFormat": "Rejected"
    }
   ]
  },
  {
   "title": "Session current count",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 13 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(tomcat_session_sessioncounter_total{job=\"$job\", instance=~\"$instance\"} - tomcat_session_expiredsessions_total)"
    }
   ]
  },
  {
   "title": "Session total created",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 16 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(tomcat_session_sessioncounter_total{job=\"$job\", instance=~\"$instance\"})"
    }
   ]
  },
  {
   "title": "Session total expired",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 19 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(tomcat_session_expiredsessions_total{job=\"$job\", instance=~\"$instance\"})"
    }
   ]
  },
  {
   "title": "Max threads",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 2, "y": 22 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "tomcat_threadpool_maxthreads{job=\"$job\", instance=~\"$instance\", protocol=\"$protocol\"}"
    }
   ]
  },
  {
   "title": "Min spare threads",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 6, "y": 22 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "tomcat_threadpool_minsparethreads{job=\"$job\", instance=~\"$instance\", protocol=\"$protocol\"}"
    }
   ]
  },
  {
   "title": "Accept count",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 10, "y": 22 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "tomcat_threadpool_acceptcount{job=\"$job\", instance=~\"$instance\", protocol=\"$protocol\"}"
    }
   ]
  },
  {
   "title": "Acceptor thread count",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 14, "y": 22 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "tomcat_threadpool_acceptorthreadcount{job=\"$job\", instance=~\"$instance\", protocol=\"$protocol\"}"
    }
   ]
  },
  {
   "title": "Poller thread count",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 18, "y": 22 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "tomcat_threadpool_pollerthreadcount{job=\"$job\", instance=~\"$instance\", protocol=\"$protocol\"}"
    }
   ]
  },
  {
   "title": "Threads",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 26 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "tomcat_threadpool_currentthreadcount{job=\"$job\", instance=~\"$instance\", protocol=~\"$protocol\"}",
     "legendFormat": "current {{protocol}}[{{port}}] {{instance}}"
    },
    {
     "expr": "tomcat_threadpool_currentthreadsbusy{job=\"$job\", instance=~\"$instance\", protocol=~\"$protocol\"}",
     "legendFormat": "current busy  {{protocol}}[{{port}}] {{instance}}"
    },
    {
     "expr": "tomcat_threadpool_connectioncount{job=\"$job\", instance=~\"$instance\", protocol=~\"$protocol\"}",
     "legendFormat": "connection  {{protocol}}[{{port}}] {{instance}}"
    },
    {
     "expr": "tomcat_threadpool_keepalivecount{job=\"$job\", instance=~\"$instance\", protocol=~\"$protocol\"}",
     "legendFormat": "keep alive  {{protocol}}[{{port}}] {{instance}}"
    }
   ]
  },
  {
   "title": "Top 5 servlet request count / 1min. rate",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 35 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "topk(5, increase(tomcat_servlet_requestcount_total{job=\"$job\", instance=~\"$instance\"}[5m]) / 5)",
     "legendFormat": "module={{module}} servlet={{servlet}}"
    }
   ]
  },
  {
   "title": "Top 5 servlet processing time",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 44 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "topk(5, rate(tomcat_servlet_processingtime_total{job=\"$job\", instance=~\"$instance\"}[5m]))",
     "legendFormat": "module={{module}} servlet={{servlet}}"
    }
   ]
  },
  {
   "title": "Top 5 servlet error count / 1min. rate",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 53 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "topk(5, increase(tomcat_servlet_errorcount_total{job=\"$job\", instance=~\"$instance\"}[5m]) / 5)",
     "legendFormat": "module={{module}} servlet={{servlet}}"
    }
   ]
  }
 ]
}