version: '3'
services:
  collectd:
    image: fr3nd/collectd
    privileged: true
    network_mode: host
    volumes:
      - /proc:/mnt/proc:ro
      - ./collectd.conf:/etc/collectd/collectd.conf

  telegraf:
    image: telegraf
    container_name: telegraf
    restart: always
    volumes:
    - ./telegraf.conf:/etc/telegraf/telegraf.conf:ro
    - //var/run/docker.sock://var/run/docker.sock
    depends_on:
      - influxdb
    links:
      - influxdb
    ports:
    - '8125:8125'

  influxdb:
    image: influxdb:1.8-alpine
    ports:
     - "8083:8083"      
     - "8086:8086"
     - "25826:25826/udp"
    volumes:
     - influxdb_data:/var/lib/influxdb
     - ./influxdb-data:/var/lib/influxdb
     - ./influxdb.conf:/etc/influxdb/influxdb.conf
     - ./types.db:/usr/share/collectd/types.db:ro
    environment:
      - INFLUXDB_DB=influx
      - INFLUXDB_ADMIN_USER=admin
      - INFLUXDB_ADMIN_PASSWORD=admin

  grafana:
    image: grafana/grafana
    container_name: grafana-server
    restart: always
    links:
      - influxdb
    ports:
      - '3000:3000'
    volumes:
      - ./grafanaprovisioning/datasources:/etc/grafana/provisioning/datasources
      - ./grafanaprovisioning/dashboards:/etc/grafana/provisioning/dashboards
      - grafana_data:/var/lib/grafana
      - ./grafana-data:/var/lib/grafana

volumes:
  grafana_data: {}
  influxdb_data: {}